baseURL = 'https://juffma.de/'
languageCode = 'en-us'
title = 'Juff-Ma Homepage'
theme = "shell"
[Params]
    description = "Juff-Ma's Homepage"
    [Params.Terminal]
        scheme = "Peppermint"

        userName = "juffma"
        pcName = "juffma.de"
        workDir = "infos"
        profile = "myself.txt"

        ps1Delay = 1
        stdoutDelay = 1 
        commandDelay = 15

        titleDelay = 2
        contentDelay = 7

        description = """
        Hello i'm Juff-Ma,
        a Programmer and You-Tuber from Germany
        """
    [Params.Tree]
        use = true
        folderName = "my_stuff"
        # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
        files = [ 
            ["C#/.NET", "/csharp/main"],
            ["Java", "/java/main"],
            ["C++", "/cpp/main"],
            ["Linux", "/linux/main"],
        ]